---
title: 'MATH411 Suggested Homework - Fall 2024'
format:
  html:
    self-contained: true
    page-layout: full
    toc: true
    toc-depth: 1
    toc-location: right
    number-sections: false
    html-math-method: katex
    embed-resources: true
    code-fold: true
    code-summary: 'Show the code'
    code-overflow: wrap
    code-copy: hover
    code-tools:
      source: false
      toggle: true
      caption: See code
engine: jupyter
preview:
  port: 3000
  browser: true
  watch-inputs: true
  navigate: true
---

# Week 1

---

**(C0-P1)** Read/work through the _Getting Started with Python_ notebook (see Modules > Homework > Getting_Started_with_Python.ipynb). Then complete the following exercises in a separate notebook or `.py` file:

a. What is the difference between the outputs generated by the following two lines of code?

```python
np.array([i for i in range(10)])
np.linspace(0, 9, 10, endpoint=True)
```

b. Use both `np.linspace()` and `np.arange()` to create an array containing floating point numbers starting at 1.0, ending at 4.0, equally spaced with separation 0.2. In other words, the array should contain 1.0, 1.2, 1.4, ..., 3.8, 4.0.

c. Create an array consisting of the floats 1.0, 2.0, 3.0, 4.0, and 5.0. Create a second array containing the square root of each of these numbers. Then, use a `for` loop to compute the sum of the squared differences between the two arrays:

$$
\sum_{i=1}^n \left(x_i - \sqrt{x_i}\right)^2
$$

**Extra Challenge**: Can you do this without a loop?

d. Starting with $x = 1$, use a `while` loop to divide by 2 until $x < 10^{-4}$. Display (print) the list 1.0, 0.5, 0.25, ..., and report the number of divisions by 2 needed such that the $(k-1)$th division produces $x > 10^{-4}$ and the $k$th division produces $x < 10^{-4}$.

e. Write code to create a function to compute $f(x) = e^{-x} \cos x$, where $x$ is a vector (array) of one or more numbers. Then evaluate $f(x)$ at the points 0, 0.1, 0.2, ..., 1.0.

f. Write code to plot the function $h(x) = e^{x} \cos^2 x - 2$ on the interval -0.5 to 5.5 and visually estimate the roots of $h(x)$ on that interval.

**(C1-P1)** Exercise 1.1.4ab  
**(C1-P2)** Exercise 1.2.2  
**(C1-P3)** Computer Problem 1.2.2ab. For each equation, find an initial point $x_0$ and a function $g(x)$ such that the fixed-point iteration $x_{k+1} = g(x_k)$ converges to $x$, where $g(x) = x$. If this is not possible, explain why.

**(C1-P4)** Exercise 1.2.14  
**(C1-P5)** Exercise 1.4.1  
**(C1-P6)** Exercise 1.4.3

# Week 2

---

**(C1-P7)** Exercise 1.4.6  
**(C1-P8)** Exercise 1.4.8  
**(C1-P9)** Computer Problem 1.4.7  
**(C1-P10)** Exercise 1.5.1  
**(C1-P11)** Use Python to compare results obtained using the Bisection Method, Newton’s Method, and the Secant Method to solve the equation $\ln x + x^2 = 3$. Note that Python code for these methods is available on I-Learn.

a. Solve the problem using each of the three methods. Report starting values and the number of iterations required to obtain 6 correct decimal places of accuracy. **Hint**: a graph of the function may help with starting values.

b. On the same axes, plot $\log(\epsilon_{i+1})$ vs. $\log(\epsilon_i)$ for the three methods. Explain your plot. How is it related to the rate or order of convergence? Use the errors to determine if your results are consistent with theory. How would you compute the error if you didn’t have an exact value for the root?

**(C3-P1)** Exercise 3.1.1ac  
**(C3-P2)** Exercise 3.1.2ac  
**(C3-P3)** Exercise 3.1.6

# Week 3

---

**(C0-P2)** Create a Python function that takes as input three points (six scalars, three pairs, or perhaps a 6-element numpy array—choose a method that makes sense to you) and uses the `matplotlib` package to create a figure window and then render a triangle with small open circles at each of the points and straight lines between each pair of circles. Include code to save your figure to a `.png` or `.jpg` file. Validate your function with the points (1, 2), (2, 1), and (2, 3).

**(C3-P4)** Exercise 3.2.2  
**(C3-P5)** Exercise 3.2.5  
**(C3-P6)** Exercise 3.2.6 **Note**: the two additional points in the next-to-last sentence should be $(x_7, y_7) = (0.1, f(0.1))$ and $(x_8, y_8) = (0.5, f(0.5))$.

**(C3-P7)** Computer Problem 3.1.3. To demonstrate that your function works, interpolate $\sin(x)$ on the interval $[-\pi, \pi]$ using nodes $-\pi, -\frac{\pi}{2}, 0, \frac{\pi}{2}, \pi$. Plot your interpolating polynomial. Plot $\sin(x)$ on the same graph, and use the numpy functions `polyfit` and `polyval` to plot an interpolating polynomial from Python on the same graph. Use a legend to make clear which curve is yours and which one came from Python. **Hint**: the code on p. 146 should help. Python versions of `newtdd` and `nest` (p. 3) are available in Canvas.

**(C3-P8)** Exercise 3.3.2ac  
**(C3-P9)** Exercise 3.3.2ac  
**(C3-P10)** Exercise 3.3.3

# Week 4

---

**(C5-P1)** Exercise 5.2.1ab  
**(C5-P2)** Exercise 5.2.2ab  
**(C5-P3)** Exercise 5.2.3ab  
**(C5-P4)** Exercise 5.2.10  
**(C5-P5)** Exercise 5.2.12  
**(C5-P6)** Computer Problem 5.2.1ac  
**(C5-P7)** Computer Problem 5.2.2de  
**(C5-P8)** Computer Problem 5.2.9bf

# Week 5

---

**(C5-P9)** Exercise 5.5.1ab  
**(C5-P10)** Exercise 5.5.4cd  
**(C5-P11)** Computer Problem 5.4.1acd  
**(C5-P12)** Computer Problem 5.4.2  
**(C5-P13)** Computer Problem 5.4.3acd  
**(C5-P14)** Exercise 5.5.5cd  
**(C5-P15)** Exercise 5.5.7

# Week 6

---

**(C2-P1)** Exercise 2.1.2ac  
**(C2-P2)** Computer Problem 2.1.2ac  
**(C2-P3)** Exercise 2.2.1ab  
**(C2-P4)** Exercise 2.2.2ab

# Week 7

---

**(C2-P5)** Exercise 2.2.4  
**(C2-P6)** Computer Problem 2.2.1ab  
**(C2-P7)** Exercise 2.4.1ab  
**(C2-P8)** Exercise 2.4.2ab  
**(C2-P9)** Exercise 2.4.4a  
**(C2-P10)** Exercise 2.4.6

# Week 8

---

**(C2-P11)** Exercise 2.5.2ab  
**(C2-P12)** Computer Problem 2.5.2 (solve using both Jacobi and Gauss-Seidel, compare results)  
**(C4-P1)** Exercise 4.1.2  
**(C4-P2)** Computer Problem 4.1.5 (also use a quadratic fit and compare)  
**(C4-P3)** Exercise 4.3.2

# Week 9

---

**(C4-P4)** Exercise 4.3.4 (use the matrix from Exercise 4.3.1d)  
**(C4-P5)** Exercise 4.3.7 (you can use your QR factorizations from Exercise 4.3.2)  
**(C4-P6)** Computer Problem 4.3.4 Additional instructions: Write a classical Gram-Schmidt code only. Use the matrices in Exercise 4.3.2 to check your code. If you use the code I provided, you must comment it (explain what every line does).

# Week 10

---

**(C4-P7)** Exercise 4.4.2  
**(C4-P8)** Exercise 4.4.3  
**(C4-P9)** Computer Problem 4.4.2 (find a preconditioned GMRES Python code and use it)

# Week 11

---

**None**  
**Exam 2 in class on Monday Week 11**  
Attempt the first several Week 12 problems before Monday Week 12

# Week 12

---

**(C10-P1)** Exercise 10.1.1ad (also, find the inverse DFT of your result, compare to the original vector)  
**(C10-P2)** Exercise 10.1.8  
**(C10-P3)** Exercise 10.2.1ab  
**(C10-P4)** Exercise 10.2.3ab  
**(C10-P5)** Exercise 10.2.3 (plot data and function to show your interpolating function does interpolate the data)  
**(C10-P6)** Computer Problem 10.2.4  
**(C10-P7)** Exercise 10.3.2ab

# Week 13

---

**(C10-P8)** Computer Problem 10.3.2cd  
**(C10-P9)** Exercise 10.3.5 (Complete the $\sum_{j=0}^{n-1} \cos \frac{2 \pi j k}{n} \cos \frac{2 \pi j l}{n}$ result only)  
**(C10-P10)** Exercise 10.1.6
